CPPE addition / modification of CircleCI orb terraform-registry

diff --git a/terraform-registry/orb.yml b/terraform-registry/orb.yml
--- a/terraform-registry/orb.yml
+++ b/terraform-registry/orb.yml
@@ -35,7 +35,7 @@ commands:
                 command: "#!/bin/bash\nset -euo pipefail\n\nexport TF_CLOUD_ORGANISATION_NAME=\"ovotech\"\nexport TF_CLOUD_REGISTRY_NAME=\"ovotech\"\nexport TF_CLOUD_API_BASE_PATH=\"https://app.terraform.io/api\"\n\n##\n# is_empty will return 0 if the environment variable passed has\n# an empty value or is missing, or 1 otherwise\nis_empty() {\n    local _TESTENV=$1\n    \n    test -z \"$(printenv \"$_TESTENV\")\"\n    return $?\n}\n\n##\n# assert_dependency will return 0 if the command is found on the path\n# or 1 if otherwise\nassert_dependency() {\n    local _DEPENDENCY=$1\n    \n    if ! command -v \"$_DEPENDENCY\" >/dev/null; then\n        echo \"Required dependency $_DEPENDENCY is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# assert_non_empty will return 0 if the environment variable passed has\n# a non-empty value or 1 if otherwise\nassert_non_empty() {\n    local _TESTENV=$1\n    \n    if is_empty \"$_TESTENV\"; then\n        echo \"Required environment variable '$_TESTENV' is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# verify_bearer_token will return 0 if the PARAM_TERRAFORM_TOKEN\n# is valid, or 2 otherwise\nverify_bearer_token() {\n    local -i _RESULT\n    \n    _RESULT=$(curl \\\n        --fail-early \\\n        --silent \\\n        --write-out '%{http_code}' \\\n        --output /dev/null \\\n        --header \"Authorization: Bearer $PARAM_TERRAFORM_TOKEN\" \\\n        --url \"$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME\"\n    )\n    \n    if [ \"$_RESULT\" -ne \"200\" ]; then\n        printf \"Fail: Unable to query the registry. Result: '%s'\\n\\nPlease review the input values and check that the Terraform Cloud credentials are correct.\\n\\n\" \"$_RESULT\"\n        return 2\n    fi\n    \n    return 0\n}\n"
                 name: Loading script dependencies
             - run:
-                command: "#!/bin/bash\nset -euo pipefail\n\nreadonly ORGANISATION_NAME=\"ovotech\"\nreadonly API_BASE_PATH=\"https://app.terraform.io/api\"\n\n##\n# is_empty will return 0 if the environment variable passed has\n# an empty value or is missing, or 1 otherwise\nis_empty() {\n    local _TESTENV=$1\n    \n    test -z \"$(printenv \"$_TESTENV\")\"\n    return $?\n}\n\n##\n# assert_dependency will return 0 if the command is found on the path\n# or 1 if otherwise\nassert_dependency() {\n    local _DEPENDENCY=$1\n    \n    if ! command -v \"$_DEPENDENCY\" >/dev/null; then\n        echo \"Required dependency $_DEPENDENCY is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# assert_non_empty will return 0 if the environment variable passed has\n# a non-empty value or 1 if otherwise\nassert_non_empty() {\n    local _TESTENV=$1\n    \n    if is_empty \"$_TESTENV\"; then\n        echo \"Required environment variable '$_TESTENV' is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# verify_bearer_token will return 0 if the PARAM_TERRAFORM_TOKEN\n# is valid, or 2 otherwise\nverify_bearer_token() {\n    local -i _RESULT\n    \n    _RESULT=$(curl \\\n        --fail-early \\\n        --silent \\\n        --write-out '%{http_code}' \\\n        --output /dev/null \\\n        --header \"Authorization: Bearer $PARAM_TERRAFORM_TOKEN\" \\\n        --url \"$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME\"\n    )\n    \n    if [ \"$_RESULT\" -ne \"200\" ]; then\n        printf \"Fail: Unable to query the registry. Result: '%s'\\n\\nPlease review the input values and check that the Terraform Cloud credentials are correct.\\n\\n\" \"$_RESULT\"\n        return 2\n    fi\n    \n    return 0\n}\n\nmodule_version_check() {\n    assert_non_empty PARAM_TERRAFORM_TOKEN || exit 2\n    assert_non_empty PARAM_MODULE_NAME || exit 2\n    assert_non_empty PARAM_MODULE_PROVIDER || exit 2\n    assert_non_empty PARAM_MODULE_VERSION || exit 2\n    \n    assert_dependency jq || exit 2\n    assert_dependency curl || exit 2\n    \n    verify_bearer_token || exit 2\n    \n    printf \"Checking for an existing version for:\\n\"\n    printf \"Module provider:   %s\\n\" \"${PARAM_MODULE_PROVIDER}\"\n    printf \"Module name:     %s\\n\" \"${PARAM_MODULE_NAME}\"\n    printf \"Module version:  %s\\n\\n\" \"${PARAM_MODULE_VERSION}\"\n    \n    _VERSION_LIST=$(curl \\\n        --fail-early \\\n        --silent \\\n        --request GET \\\n        --header \"Authorization: Bearer ${PARAM_TERRAFORM_TOKEN}\" \\\n        --header \"Content-Type: application/vnd.api+json\" \\\n    \"$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME/registry-modules/private/$ORGANISATION_NAME/${PARAM_MODULE_NAME}/${PARAM_MODULE_PROVIDER}\") || _EC=$?\n    \n    if [[ \"${_EC:-0}\" -ne 0 ]]; then\n        printf \"Fail: Unable to query the registry for module:'%s' provider:'%s'.\\n\\nPlease review the input values and check that the Terraform Cloud credentials are correct.\\n\\n\" \"${PARAM_MODULE_NAME}\" \"${PARAM_PROVIDER_NAME}\"\n        exit 2\n    fi\n    \n    EXISTING_VERSION=$(echo \"$_VERSION_LIST\" | jq --arg version \"${PARAM_MODULE_VERSION}\" -c '.data.attributes.\"version-statuses\"[]? | select(.version == $version)')\n    if [[ -n \"${EXISTING_VERSION}\" ]]; then\n        printf  \"Fail: Version '%s' has already been published to Terraform Cloud.\\n\\n\" \"${PARAM_MODULE_VERSION}\"\n        return 1\n    fi\n    \n    printf  \"Success: Version '%s' can be published to Terraform Cloud.\\n\\n\" \"${PARAM_MODULE_VERSION}\"\n    return 0\n}\n\n# Will not run if sourced for bats-core tests.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*\"$ORB_TEST_ENV\"}\" == \"$0\" ]; then\n    module_version_check\nfi\n"
+                command: "#!/bin/bash\nset -euo pipefail\n\n## Requires common.sh to be in scope for environment variables and common functions.\n\n##\n# is_empty will return 0 if the environment variable passed has\n# an empty value or is missing, or 1 otherwise\nis_empty() {\n    local _TESTENV=$1\n    \n    test -z \"$(printenv \"$_TESTENV\")\"\n    return $?\n}\n\n##\n# assert_dependency will return 0 if the command is found on the path\n# or 1 if otherwise\nassert_dependency() {\n    local _DEPENDENCY=$1\n    \n    if ! command -v \"$_DEPENDENCY\" >/dev/null; then\n        echo \"Required dependency $_DEPENDENCY is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# assert_non_empty will return 0 if the environment variable passed has\n# a non-empty value or 1 if otherwise\nassert_non_empty() {\n    local _TESTENV=$1\n    \n    if is_empty \"$_TESTENV\"; then\n        echo \"Required environment variable '$_TESTENV' is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\nmodule_version_check() {\n    assert_non_empty PARAM_TERRAFORM_TOKEN || exit 2\n    assert_non_empty PARAM_MODULE_NAME || exit 2\n    assert_non_empty PARAM_MODULE_PROVIDER || exit 2\n    assert_non_empty PARAM_MODULE_VERSION || exit 2\n    \n    assert_dependency jq || exit 2\n    assert_dependency curl || exit 2\n    \n    verify_bearer_token || exit 2\n    \n    printf \"Checking for an existing version for:\\n\"\n    printf \"Module provider:   %s\\n\" \"${PARAM_MODULE_PROVIDER}\"\n    printf \"Module name:     %s\\n\" \"${PARAM_MODULE_NAME}\"\n    printf \"Module version:  %s\\n\\n\" \"${PARAM_MODULE_VERSION}\"\n    \n    _VERSION_LIST=$(curl \\\n        --fail-early \\\n        --silent \\\n        --request GET \\\n        --header \"Authorization: Bearer ${PARAM_TERRAFORM_TOKEN}\" \\\n        --header \"Content-Type: application/vnd.api+json\" \\\n    \"$TF_CLOUD_API_BASE_PATH/v2/organizations/$TF_CLOUD_ORGANISATION_NAME/registry-modules/private/$TF_CLOUD_REGISTRY_NAME/${PARAM_MODULE_NAME}/${PARAM_MODULE_PROVIDER}\") || _EC=$?\n    \n    if [[ \"${_EC:-0}\" -ne 0 ]]; then\n        printf \"Fail: Unable to query the registry for module:'%s' provider:'%s'.\\n\\nPlease review the input values and check that the Terraform Cloud credentials are correct.\\n\\n\" \"${PARAM_MODULE_NAME}\" \"${PARAM_PROVIDER_NAME}\"\n        exit 2\n    fi\n    \n    EXISTING_VERSION=$(echo \"$_VERSION_LIST\" | jq --arg version \"${PARAM_MODULE_VERSION}\" -c '.data.attributes.\"version-statuses\"[]? | select(.version == $version)')\n    if [[ -n \"${EXISTING_VERSION}\" ]]; then\n        printf  \"Fail: Version '%s' has already been published to Terraform Cloud.\\n\\n\" \"${PARAM_MODULE_VERSION}\"\n        return 1\n    fi\n    \n    printf  \"Success: Version '%s' can be published to Terraform Cloud.\\n\\n\" \"${PARAM_MODULE_VERSION}\"\n    return 0\n}\n\n# Will not run if sourced for bats-core tests.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*\"$ORB_TEST_ENV\"}\" == \"$0\" ]; then\n    module_version_check\nfi\n"
                 environment:
                     PARAM_MODULE_NAME: <<parameters.module_name>>
                     PARAM_MODULE_PROVIDER: <<parameters.module_provider>>
@@ -79,52 +79,15 @@ commands:
                     echo "export PARAM_TERRAFORM_TOKEN=$(echo ${<< parameters.token >>})" >> $BASH_ENV
                 name: Setting variables
             - run:
+                command: "#!/bin/bash\nset -euo pipefail\n\nexport TF_CLOUD_ORGANISATION_NAME=\"ovotech\"\nexport TF_CLOUD_REGISTRY_NAME=\"ovotech\"\nexport TF_CLOUD_API_BASE_PATH=\"https://app.terraform.io/api\"\n\n##\n# is_empty will return 0 if the environment variable passed has\n# an empty value or is missing, or 1 otherwise\nis_empty() {\n    local _TESTENV=$1\n    \n    test -z \"$(printenv \"$_TESTENV\")\"\n    return $?\n}\n\n##\n# assert_dependency will return 0 if the command is found on the path\n# or 1 if otherwise\nassert_dependency() {\n    local _DEPENDENCY=$1\n    \n    if ! command -v \"$_DEPENDENCY\" >/dev/null; then\n        echo \"Required dependency $_DEPENDENCY is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# assert_non_empty will return 0 if the environment variable passed has\n# a non-empty value or 1 if otherwise\nassert_non_empty() {\n    local _TESTENV=$1\n    \n    if is_empty \"$_TESTENV\"; then\n        echo \"Required environment variable '$_TESTENV' is missing.\"\n        return 1\n    fi\n    \n    return 0\n}\n\n##\n# verify_bearer_token will return 0 if the PARAM_TERRAFORM_TOKEN\n# is valid, or 2 otherwise\nverify_bearer_token() {\n    local -i _RESULT\n    \n    _RESULT=$(curl \\\n        --fail-early \\\n        --silent \\\n        --write-out '%{http_code}' \\\n        --output /dev/null \\\n        --header \"Authorization: Bearer $PARAM_TERRAFORM_TOKEN\" \\\n        --url \"$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME\"\n    )\n    \n    if [ \"$_RESULT\" -ne \"200\" ]; then\n        printf \"Fail: Unable to query the registry. Result: '%s'\\n\\nPlease review the input values and check that the Terraform Cloud credentials are correct.\\n\\n\" \"$_RESULT\"\n        return 2\n    fi\n    \n    return 0\n}\n"
+                name: Loading script dependencies
+            - run:
                 command: |
                     #!/bin/bash
                     set -euo pipefail
 
-                    readonly ORGANISATION_NAME="ovotech"
-                    readonly API_BASE_PATH="https://app.terraform.io/api"
+                    ## Requires common.sh to be in scope for environment variables and common functions.
 
-                    ##
-                    # is_empty will return 0 if the environment variable passed has
-                    # an empty value or is missing, or 1 otherwise
-                    is_empty() {
-                        local _TESTENV=$1
-
-                        test -z "$(printenv "$_TESTENV")"
-                        return $?
-                    }
-
-                    ##
-                    # assert_dependency will return 0 if the command is found on the path
-                    # or 1 if otherwise
-                    assert_dependency() {
-                        local _DEPENDENCY=$1
-
-                        if ! command -v "$_DEPENDENCY" >/dev/null; then
-                            echo "Required dependency $_DEPENDENCY is missing."
-                            return 1
-                        fi
-
-                        return 0
-                    }
-
-                    ##
-                    # assert_non_empty will return 0 if the environment variable passed has
-                    # a non-empty value or 1 if otherwise
-                    assert_non_empty() {
-                        local _TESTENV=$1
-
-                        if is_empty "$_TESTENV"; then
-                            echo "Required environment variable '$_TESTENV' is missing."
-                            return 1
-                        fi
-
-                        return 0
-                    }
-
-                    ##
                     # module_exists will return true if the module exists
                     # in Terraform cloud, or otherwise false
                     # Expected params:
@@ -142,7 +105,7 @@ commands:
                             --write-out '%{http_code}' \
                             --silent \
                             --output /dev/null \
-                            --url "$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME/registry-modules/private/$ORGANISATION_NAME/$_MODULE_NAME/$_MODULE_PROVIDER_NAME"
+                            --url "$TF_CLOUD_API_BASE_PATH/v2/organizations/$TF_CLOUD_ORGANISATION_NAME/registry-modules/private/$TF_CLOUD_REGISTRY_NAME/$_MODULE_NAME/$_MODULE_PROVIDER_NAME"
                         )
 
                         if [ "$_RESULT" -eq "200" ]; then
@@ -171,7 +134,7 @@ commands:
                             --header "Authorization: Bearer $PARAM_TERRAFORM_TOKEN" \
                             --header "Content-Type: application/vnd.api+json" \
                             --silent \
-                            --url "$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME/registry-modules/private/$ORGANISATION_NAME/$_MODULE_NAME/$_MODULE_PROVIDER_NAME"
+                            --url "$TF_CLOUD_API_BASE_PATH/v2/organizations/$TF_CLOUD_ORGANISATION_NAME/registry-modules/private/$TF_CLOUD_REGISTRY_NAME/$_MODULE_NAME/$_MODULE_PROVIDER_NAME"
                         )
 
                         local _EXISTING_VERSION
@@ -221,7 +184,7 @@ commands:
                             --silent \
                             --max-time 5 \
                             --data "${_DATA}" \
-                            --url "$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME/registry-modules/private/$ORGANISATION_NAME/$_MODULE_NAME/$_MODULE_PROVIDER_NAME/versions"
+                            --url "$TF_CLOUD_API_BASE_PATH/v2/organizations/$TF_CLOUD_ORGANISATION_NAME/registry-modules/private/$TF_CLOUD_REGISTRY_NAME/$_MODULE_NAME/$_MODULE_PROVIDER_NAME/versions"
                         )
 
                         echo "$_RESULT" | jq -c -r '.data.links.upload'
@@ -306,29 +269,6 @@ commands:
 
                         printf "Unable to determine module version from parameters.\n"
                         return 2
-                    }
-
-                    ##
-                    # verify_bearer_token will return 0 if the PARAM_TERRAFORM_TOKEN
-                    # is valid, or 2 otherwise
-                    verify_bearer_token() {
-                        local -i _RESULT
-
-                        _RESULT=$(curl \
-                            --fail-early \
-                            --silent \
-                            --write-out '%{http_code}' \
-                            --output /dev/null \
-                            --header "Authorization: Bearer $PARAM_TERRAFORM_TOKEN" \
-                            --url "$API_BASE_PATH/v2/organizations/$ORGANISATION_NAME"
-                        )
-
-                        if [ "$_RESULT" -ne "200" ]; then
-                            printf "Fail: Unable to query the registry. Result: '%s'\n\nPlease review the input values and check that the Terraform Cloud credentials are correct.\n\n" "$_RESULT"
-                            return 2
-                        fi
-
-                        return 0
                     }
 
                     publish() {
