CPPE addition / modification of CircleCI orb sast

diff --git a/sast/orb.yml b/sast/orb.yml
--- a/sast/orb.yml
+++ b/sast/orb.yml
@@ -112,7 +112,7 @@ commands:
             - checkout
             - install_hadolint
             - run:
-                command: "#!/bin/bash\nscan_dockerfile() {\n    set --\n    if [ -n \"$PARAM_IGNORE_RULES\" ]; then\n        IFS=, read -ra IGNORE_RULES \\<<< \"$PARAM_IGNORE_RULES\"\n        for RULE in \"${IGNORE_RULES[@]}\"; do\n          set -- \"$@\" \"--ignore\" \"${RULE}\"\n        done\n    fi\n\n    if [ -n \"$PARAM_TRUSTED_REGISTRIES\" ]; then\n        IFS=, read -ra TRUSTED_REGISTRIES \\<<< \"$PARAM_TRUSTED_REGISTRIES\"\n        for TRUSTED_REGISTRY in \"${TRUSTED_REGISTRIES[@]}\"; do\n          set -- \"$@\" \"--trusted-registry\" \"${TRUSTED_REGISTRY}\"\n        done\n    fi\n    printf '%s\\n' \"Running hadolint on $PARAM_DOCKERFILE\"\n\n    if [ ! -d \"./reports/sast/docker\" ]; then\n        mkdir -p ./reports/sast/docker\n    fi\n\n    hadolint --no-fail \"$@\" \"$PARAM_DOCKERFILE\"\n    hadolint --format json \"$@\" \"$PARAM_DOCKERFILE\" 1> \"./reports/sast/docker/$(date +%s).json\"\n\n    local STATUS_CODE=$?\n    if [ $STATUS_CODE -eq 0 ]; then\n        printf '%s\\n' \"Docker file scan succeeded with no linting issues!!!\"\n    else\n        printf '%s\\n' \"Docker file scan failed with linting issues, see report folder!!!\" \n        return $STATUS_CODE\n    fi\n}\n\n# Will not run if sourced for bats-core tests.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*\"$ORB_TEST_ENV\"}\" == \"$0\" ]; then\n    scan_dockerfile   \nfi\n"
+                command: "#!/bin/bash\nscan_dockerfile() {\n    set --\n    if [ -n \"$PARAM_IGNORE_RULES\" ]; then\n        IFS=, read -ra IGNORE_RULES \\<<< \"$PARAM_IGNORE_RULES\"\n        for RULE in \"${IGNORE_RULES[@]}\"; do\n          set -- \"$@\" \"--ignore\" \"${RULE}\"\n        done\n    fi\n\n    if [ -n \"$PARAM_TRUSTED_REGISTRIES\" ]; then\n        IFS=, read -ra TRUSTED_REGISTRIES \\<<< \"$PARAM_TRUSTED_REGISTRIES\"\n        for TRUSTED_REGISTRY in \"${TRUSTED_REGISTRIES[@]}\"; do\n          set -- \"$@\" \"--trusted-registry\" \"${TRUSTED_REGISTRY}\"\n        done\n    fi\n    printf '%s\\n' \"Running hadolint on $PARAM_DOCKERFILE\"\n\n    if [ ! -d \"./reports/sast/docker\" ]; then\n        mkdir -p ./reports/sast/docker\n    fi\n\n    hadolint --no-fail \"$@\" \"$PARAM_DOCKERFILE\"\n    hadolint --format json \"$@\" \"$PARAM_DOCKERFILE\" 1> \"./reports/sast/docker/$(date \"+%F-%H-%M-%S\").json\"\n\n    local STATUS_CODE=$?\n    if [ $STATUS_CODE -eq 0 ]; then\n        printf '%s\\n' \"Docker file scan succeeded with no linting issues!!!\"\n    else\n        printf '%s\\n' \"Docker file scan failed with linting issues, see report folder!!!\" \n        return $STATUS_CODE\n    fi\n}\n\n# Will not run if sourced for bats-core tests.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*\"$ORB_TEST_ENV\"}\" == \"$0\" ]; then\n    scan_dockerfile   \nfi\n"
                 environment:
                     PARAM_DOCKERFILE: <<parameters.dockerfile>>
                     PARAM_IGNORE_RULES: <<parameters.ignore-rules>>
@@ -149,7 +149,7 @@ commands:
                       fi
 
                       semgrep scan "$@" --error "${PARAM_DIRECTORY}" || _EC=$?
-                      semgrep scan "$@" --disable-nosem --json --output "./reports/sast/scala/$(date +%s).json" "${PARAM_DIRECTORY}"
+                      semgrep scan "$@" --disable-nosem --json --output "./reports/sast/scala/$(date "+%F-%H-%M-%S").json" "${PARAM_DIRECTORY}"
 
                       if [[ "${_EC:-0}" -gt 0 ]]; then
                         echo "Semgrep scan returned failures. See logs."
@@ -223,7 +223,7 @@ commands:
                         fi
 
                         export LOG_LEVEL="WARNING"
-                        checkov -d "$PARAM_DIRECTORY" --quiet --output json --soft-fail "$@" 1> "./reports/sast/terraform/$(date +%s).json"
+                        checkov -d "$PARAM_DIRECTORY" --quiet --output json --soft-fail "$@" 1> "./reports/sast/terraform/$(date "+%F-%H-%M-%S").json"
                         checkov -d "$PARAM_DIRECTORY" --quiet "$@"
                     }
 
