CPPE addition / modification of CircleCI orb sast

diff --git a/sast/orb.yml b/sast/orb.yml
--- a/sast/orb.yml
+++ b/sast/orb.yml
@@ -62,14 +62,14 @@ commands:
                     hadolint -v
                 name: Install latest version of Hadolint
             - run:
-                command: "#!/bin/bash\nscan_dockerfile() {\n    set --\n    if [ -n \"$PARAM_IGNORE_RULES\" ]; then\n        IFS=, read -ra IGNORE_RULES \\<<< \"$PARAM_IGNORE_RULES\"\n        for RULE in \"${IGNORE_RULES[@]}\"; do\n          set -- \"$@\" \"--ignore\" \"${RULE}\"\n        done\n    fi\n\n    if [ -n \"$PARAM_TRUSTED_REGISTRIES\" ]; then\n        IFS=, read -ra TRUSTED_REGISTRIES \\<<< \"$PARAM_TRUSTED_REGISTRIES\"\n        for TRUSTED_REGISTRY in \"${TRUSTED_REGISTRIES[@]}\"; do\n          set -- \"$@\" \"--trusted-registry\" \"${TRUSTED_REGISTRY}\"\n        done\n    fi\n    printf '%s\\n' \"Running hadolint on $PARAM_DOCKERFILE\"\n\n    if [ ! -d \"./reports_sast_docker\" ]; then\n        mkdir -p ./reports_sast_docker\n    fi\n\n    hadolint --no-fail \"$@\" \"$PARAM_DOCKERFILE\"\n    hadolint --format json \"$@\" \"$PARAM_DOCKERFILE\" 1> ./reports_sast_docker/${RANDOM}.json\n\n    local STATUS_CODE=$?\n    if [ $STATUS_CODE -eq 0 ]; then\n        printf '%s\\n' \"Docker file scan succeeded with no linting issues!!!\"\n    else\n        printf '%s\\n' \"Docker file scan failed with linting issues, see report folder!!!\" \n        return $STATUS_CODE\n    fi\n}\n\n# Will not run if sourced for bats-core tests.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*\"$ORB_TEST_ENV\"}\" == \"$0\" ]; then\n    scan_dockerfile   \nfi\n"
+                command: "#!/bin/bash\nscan_dockerfile() {\n    if [ -n \"$PARAM_IGNORE_RULES\" ]; then\n        readonly ignore_rules=$(printf '%s' \"--ignore ${PARAM_IGNORE_RULES//,/ --ignore }\")\n    fi\n\n    if [ -n \"$PARAM_TRUSTED_REGISTRIES\" ]; then\n        readonly trusted_registries=$(printf '%s' \"--trusted-registry ${PARAM_TRUSTED_REGISTRIES//,/ --trusted-registry }\")\n    fi\n    printf '%s\\n' \"Running hadolint on $PARAM_DOCKERFILE\"\n\n    if [ ! -d \"./reports_sast_docker\" ]; then\n        mkdir -p ./reports_sast_docker\n    fi\n\n    hadolint --no-fail \\\n    ${PARAM_IGNORE_RULES:+$ignore_rules} \\\n    ${PARAM_TRUSTED_REGISTRIES:+$trusted_registries} \\\n    $PARAM_DOCKERFILE\n\n    hadolint --format json \\\n    ${PARAM_IGNORE_RULES:+$ignore_rules} \\\n    ${PARAM_TRUSTED_REGISTRIES:+$trusted_registries} \\\n    $PARAM_DOCKERFILE 1> ./reports_sast_docker/${RANDOM}.json\n\n    local STATUS_CODE=$?\n    if [ $STATUS_CODE -eq 0 ]; then\n        printf '%s\\n' \"Docker file scan succeeded with no linting issues!!!\"\n    else\n        printf '%s\\n' \"Docker file scan failed with linting issues, see report folder!!!\" \n        exit $STATUS_CODE\n    fi\n}\n\n# Will not run if sourced for bats-core tests.\nORB_TEST_ENV=\"bats-core\"\nif [ \"${0#*$ORB_TEST_ENV}\" == \"$0\" ]; then\n    scan_dockerfile   \nfi\n"
                 environment:
                     PARAM_DOCKERFILE: <<parameters.dockerfile>>
                     PARAM_IGNORE_RULES: <<parameters.ignore-rules>>
                     PARAM_TRUSTED_REGISTRIES: <<parameters.trusted-registries>>
                 name: Lint <<parameters.dockerfile>> with hadolint
             - store_artifacts:
-                path: ./reports_sast_docker/
+                path: ./reports/sast/docker/
     scan_scala:
         description: |
             Scans a Scala project using Semgrep
@@ -117,6 +117,81 @@ commands:
                 name: Lint Scala code in <<parameters.directory>> with Semgrep
             - store_artifacts:
                 path: ./reports/sast/scala/
+    scan_terraform:
+        description: |
+            Run Checkov Infrastructure as code static analysis against a directory
+        parameters:
+            baseline:
+                default: ""
+                description: Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline
+                type: string
+            config_file:
+                default: ""
+                description: checkov configuration file
+                type: string
+            directory:
+                default: .
+                description: directory with infrastructure code to scan
+                type: string
+        steps:
+            - checkout
+            - run:
+                command: pip3 install checkov
+                name: Install Checkov command line
+            - run:
+                command: |+
+                    #!/bin/bash
+
+                    run_checkov() {
+                        checkov --version
+
+                        set --
+                        set -- "$@" "--output" "cli"
+                        set -- "$@" "--framework" "terraform"
+                        set -- "$@" "--download-external-modules" "false"
+
+                        if [ -z "$PARAM_BASELINE" ]; then
+                            DEFAULT_BASELINE=$(find "$PARAM_DIRECTORY" -name ".checkov.baseline")
+                            if [ -n "$DEFAULT_BASELINE" ]; then
+                                set -- "$@" "--baseline" "$DEFAULT_BASELINE"
+                            else
+                                DEFAULT_BASELINE=$(find . -name ".checkov.baseline")
+                                if [ -n "$DEFAULT_BASELINE" ]; then
+                                    set -- "$@" "--baseline" "$DEFAULT_BASELINE"
+                                fi
+                            fi
+                        else
+                            set -- "$@" "--baseline" "$PARAM_BASELINE"
+                        fi
+
+                        if [[ -n "$PARAM_CONFIG_FILE" ]]; then
+                            set -- "$@" "--config-file" "$PARAM_CONFIG_FILE"
+                        fi
+
+                        echo "running checkov on directory $PARAM_DIRECTORY:"
+                        echo "checkov -d $PARAM_DIRECTORY --quiet" "$@"
+                        if [ ! -d "./reports_sast_terraform" ]; then
+                            mkdir -p ./reports_sast_terraform
+                        fi
+
+                        export LOG_LEVEL="WARNING"
+                        checkov -d "$PARAM_DIRECTORY" --quiet --output json --soft-fail "$@" 1> ./reports_sast_terraform/${RANDOM}.json
+                        checkov -d "$PARAM_DIRECTORY" --quiet "$@"
+                    }
+
+                    # Will not run if sourced for bats-core tests.
+                    ORB_TEST_ENV="bats-core"
+                    if [ "${0#*"$ORB_TEST_ENV"}" == "$0" ]; then
+                        run_checkov
+                    fi
+
+                environment:
+                    PARAM_BASELINE: <<parameters.baseline>>
+                    PARAM_CONFIG_FILE: <<parameters.config_file>>
+                    PARAM_DIRECTORY: <<parameters.directory>>
+                name: Run Checkov command line
+            - store_artifacts:
+                path: ./reports/sast/terraform/
 executors:
     default:
         description: |
@@ -213,10 +288,32 @@ jobs:
                         at: <<parameters.workspace-root>>
             - scan_scala:
                 directory: <<parameters.directory>>
+    scan_terraform:
+        description: |
+            Scans terraform files using Checkov Infrastructure as code static analysis against a directory
+        executor: default
+        parameters:
+            baseline:
+                default: ""
+                description: Path to a .checkov.baseline file to compare. Report will include only failed checks that are not in the baseline
+                type: string
+            config_file:
+                default: ""
+                description: checkov configuration file
+                type: string
+            directory:
+                default: .
+                description: directory with infrastructure code to scan
+                type: string
+        steps:
+            - scan_terraform:
+                baseline: << parameters.baseline >>
+                config_file: << parameters.config_file >>
+                directory: << parameters.directory >>
 examples:
     scan_dockerfile_example:
         description: |
-            Sample usage of Docker orb.
+            Sample usage of scanning a Dockerfile.
         usage:
             version: "2.1"
             orbs:
@@ -240,4 +337,16 @@ examples:
                     jobs:
                         - sast/scan_scala:
                             directory: ./src
+    scan_terraform:
+        description: |
+            Sample usage of scanning Terraform files.
+        usage:
+            version: "2.1"
+            orbs:
+                sast: ovotech/sast@1
+            workflows:
+                example-workflow:
+                    jobs:
+                        - sast/scan_terraform:
+                            directory: terraform/examples
 
